name: Pipeline para revisar archivo

on:
  push:
    branches: ["main"]

jobs:
  saludos:
    runs-on: ubuntu-latest

    steps:
      - name: checkout del codigo
        uses: actions/checkout@v4

      - name: Usar NODE JS
        uses: actions/setup-node@v3
        with:
          node-version: "24"
      
      - name: Construir app con node
        run: npm install
